export default [
  { name: "AM", path: require("../assets/A_major.png") },
  { name: "Am", path: require("../assets/A_minor.png") },
  { name: "AbM", path: require("../assets/Ab_major.png") },
  { name: "Abm", path: require("../assets/Ab_minor.png") },
  { name: "BM", path: require("../assets/B_major.png") },
  { name: "Bm", path: require("../assets/B_minor.png") },
  { name: "BbM", path: require("../assets/Bb_major.png") },
  { name: "Bbm", path: require("../assets/Bb_minor.png") },
  { name: "CM", path: require("../assets/C_major.png") },
  { name: "Cm", path: require("../assets/C_minor.png") },
  { name: "DM", path: require("../assets/D_major.png") },
  { name: "Dm", path: require("../assets/D_minor.png") },
  { name: "DbM", path: require("../assets/Db_major.png") },
  { name: "EM", path: require("../assets/E_major.png") },
  { name: "Em", path: require("../assets/E_minor.png") },
  { name: "EbM", path: require("../assets/Eb_major.png") },
  { name: "FM", path: require("../assets/F_major.png") },
  { name: "Fm", path: require("../assets/F_minor.png") },
  { name: "F#M", path: require("../assets/F_sharp_major.png") },
  { name: "F#m", path: require("../assets/F_sharp_minor.png") },
  { name: "GM", path: require("../assets/G_major.png") },
  { name: "Gm", path: require("../assets/G_minor.png") },
];
